import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useEffect, useRef, useState } from "react";
import { ToastContainer, toast } from "react-toastify";
import copy from "copy-to-clipboard";
import "react-toastify/dist/ReactToastify.css";
import Spotify from "@/Components/Logos/Spotify";
import Youtube from "@/Components/Logos/Youtube";
import Instagram from "@/Components/Logos/Instagram";
import Discord from "@/Components/Logos/Discord";
import axios from "axios";
export default function Home() {
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [number, setNumber] = useState("");
  const [subject, setSubject] = useState("");
  const [message, setMessage] = useState("");

  // Form validation

  async function messageHandler(e) {
    e.preventDefault();
    let emailRegex = /^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/;
    let phoneRegex = /^[\+\(\s.\-\/\d\)]{5,30}$/;

    if (name === "") {
      return toast.error("Please enter a name", { theme: "dark" });
    }
    if (email === "") {
      return toast.error("Please enter an email", { theme: "dark" });
    }
    if (!emailRegex.test(email)) {
      return toast.error("Please enter a valid phone number", {
        theme: "dark",
      });
    }
    if (number !== "" && !phoneRegex.test(number)) {
      return toast.error("Please enter a valid phone number", {
        theme: "dark",
      });
    }
    if (subject === "") {
      return toast.error("Please mention a subject", { theme: "dark" });
    }
    if (message === "") {
      return toast.error("Please write a message", { theme: "dark" });
    }
    // Posting using axios
    await axios.post("/api/add", {
      name: name,
      email: email,
      number: number,
      subject: subject,
      message: message,
    });

    return toast.success(
      "Message sent! I will get right back with you momentarily!",
      {
        theme: "dark",
      }
    );
  }

  useEffect(() => {}, []);

  return (
    <>
      <Head>
        <title>The Formante - Recording Services</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <section
          style={{ paddingTop: "0" }}
          className={`${styles.section} ${styles.intro} `}
        >
          <div className={` ${styles.center}`}>
            <div className={`${styles.content}`}>
              <div className={styles.introWrapper}>
                <div className={styles.introFiler}></div>
                <Image
                  src={"/images/1.jpg"}
                  alt={"bruh"}
                  fill
                  sizes="(max-width: 768px) 100vw,"
                  className={styles.mainImage}
                />
              </div>
            </div>
          </div>
        </section>
        <section className={`${styles.section} ${styles.work}`}>
          <h1 className={styles.sectionHeading}>Work</h1>
          <div className={styles.center}>
            <div className={`${styles.workGrid} ${styles.content}`}>
              <div className={styles.workItem}>
                <div className={styles.center}>
                  <div className={styles.embeder}>
                    <iframe
                      width="100% "
                      height="100%"
                      src="https://www.youtube.com/embed/-FEW5xcJ8aw"
                      title="YouTube video player"
                      frameBorder="0"
                      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                      allowFullScreen
                    ></iframe>
                  </div>
                </div>
                <div className={styles.workItemText}>
                  <h1>{`IX FALL$ - ITCH (feat. Misheard) [Candy Heist Remix]`}</h1>
                  <p>Produced, Mixed & Mastered</p>
                </div>
              </div>
              <div className={styles.workItem}>
                <div className={styles.center}>
                  <div className={styles.embeder}>
                    <iframe
                      width="100%"
                      height="100%"
                      src="https://www.youtube.com/embed/lt4IJCDV7GI?start=3"
                      title="YouTube video player"
                      frameBorder="0"
                      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                      allowFullScreen
                    ></iframe>
                  </div>
                </div>
                <div className={styles.workItemText}>
                  <h1>{`Shreysht & Vrun - Angelina Jolie `}</h1>
                  <p>Mixed and Mastered</p>
                </div>
              </div>
              <div className={styles.workItem}>
                <div className={styles.center}>
                  <div className={styles.edmbeer}>
                    <iframe
                      width="100%"
                      height="100%"
                      src="https://www.youtube.com/embed/fC8QdHKArJ0?start=3"
                      title="YouTube video player"
                      frameBorder="0"
                      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                      allowFullScreen
                    ></iframe>
                  </div>
                </div>
                <div className={styles.workItemText}>
                  <h1>{`Street Academics - Walayar`}</h1>
                  <p>Mixed and Mastered</p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className={`${styles.section} ${styles.clientele}`}>
          <h1 className={styles.sectionHeading}>Clientele</h1>
          <div className={styles.center}>
            <div className={`${styles.clientGrid} ${styles.content}`}>
              <div className={styles.imageWrapper}>
                <div className={styles.filer}></div>
                <div className={styles.text}>
                  <p>Street Academics</p>
                </div>
                <div className={styles.hoverText}>
                  <h1 className={styles.heading}>Street Academics</h1>
                  <p className={styles.subheading}>Mixing & Mastering</p>
                </div>
                <Image
                  src={"/images/image2.jpeg"}
                  alt={"bruh"}
                  priority
                  placeholder="blur"
                  blurDataURL={"/images/image2.jpeg"}
                  fill
                  className={styles.image}
                />
              </div>
              <div className={styles.imageWrapper}>
                <div className={styles.filer}></div>
                <div className={styles.text}>
                  <p>Pina Colada Blues</p>
                </div>
                <div className={styles.hoverText}>
                  <h1 className={styles.heading}>Pina Colada Blues</h1>
                  <p className={styles.subheading}>Mastering</p>
                </div>
                <Image
                  src={"/images/image1.jpeg"}
                  alt={"bruh"}
                  style={{ objectPosition: "50% 20%" }}
                  fill
                  sizes="(max-width: 768px) 100vw,"
                  className={styles.image}
                />
              </div>
              <div className={styles.imageWrapper}>
                <div className={styles.filer}></div>
                <div className={styles.text}>
                  <p>Sampreet</p>
                </div>
                <div className={styles.hoverText}>
                  <h1 className={styles.heading}>Sampreet</h1>
                  <p className={styles.subheading}>Mixing & Mastering</p>
                </div>
                <Image
                  src={"/images/image3.png"}
                  alt={"bruh"}
                  fill
                  sizes="(max-width: 768px) 100vw,"
                  className={styles.image}
                />
              </div>
              <div className={styles.imageWrapper}>
                <div className={styles.filer}></div>
                <div className={styles.text}>
                  <p>Nihal Sadiq</p>
                </div>
                <div className={styles.hoverText}>
                  <h1 className={styles.heading}>Nihal Sadiq</h1>
                  <p className={styles.subheading}>
                    Production, Mixing & Mastering
                  </p>
                </div>
                <Image
                  src={"/images/image4.jpg"}
                  alt={"bruh"}
                  fill
                  style={{ objectPosition: "50% 20%" }}
                  sizes="(max-width: 768px) 100vw,"
                  className={styles.image}
                />
              </div>
            </div>
          </div>
        </section>
        <section className={`${styles.section} ${styles.contact}`}>
          <h1 className={styles.sectionHeading}>Contact me</h1>
          <div className={`${styles.content}`} style={{ marginInline: "auto" }}>
            <header className={styles.contactHeader}>
              <h1>
                {
                  "Have a question, idea or want to work together on a project? Let's talk!"
                }
              </h1>
            </header>
            <form className={styles.form}>
              <input
                type="text"
                className={styles.input}
                autoComplete="new-password"
                value={name}
                placeholder="Name*"
                onChange={(e) => {
                  setName(e.target.value);
                }}
              />
              <input
                type="email"
                value={email}
                className={styles.input}
                placeholder="Email*"
                autoComplete="new-password"
                onChange={(e) => setEmail(e.target.value)}
              />
              <input
                type="text"
                value={`${number}`}
                className={styles.input}
                placeholder="Phone Number"
                autoComplete="new-password"
                onChange={(e) => setNumber(e.target.value)}
              />
              <input
                type="text"
                value={subject}
                className={styles.input}
                placeholder="Subject*"
                autoComplete="new-password"
                onChange={(e) => setSubject(e.target.value)}
              />
              <textarea
                value={message}
                onChange={(e) => setMessage(e.target.value)}
                className={`${styles.input} ${styles.textArea}`}
                placeholder="Message*"
                autoComplete="new-password"
              />
              <div
                className={styles.formBtn}
                onClick={(e) => messageHandler(e)}
              >
                <div className={styles.btnText}>Send</div>
              </div>
            </form>
            <div className={styles.contactInfo}>
              <div className={styles.contactTextinfo}>
                <div
                  className={styles.contactText}
                  onClick={() => {
                    copy("formantemusic@gmail.com");
                    toast.success("Copied Email!", {
                      theme: "dark",
                    });
                  }}
                >
                  formantemusic@gmail.com
                </div>
                <div
                  className={styles.contactText}
                  onClick={() => {
                    copy("+1 782-882-5427");
                    toast.success("Copied Number!", { theme: "dark" });
                  }}
                >
                  +1 782-882-5427
                </div>
              </div>
              <div className={styles.logos}>
                <div
                  className={styles.contactLogo}
                  onClick={() => {
                    copy("The Formante#3389");
                    toast.success("Copied discord tag!", { theme: "dark" });
                  }}
                >
                  <Discord />
                </div>
                <Link
                  href="https://www.instagram.com/theformante/"
                  passHref={true}
                  target="_blank"
                >
                  <div className={styles.contactLogo}>
                    <Instagram />
                  </div>
                </Link>
                <Link
                  href="https://open.spotify.com/artist/6t7uj5uSApVdULpiJLK1sR?si=dc164fdcf6844564"
                  passHref={true}
                  target="_blank"
                >
                  <div className={styles.contactLogo}>
                    <Spotify />
                  </div>
                </Link>
                <Link
                  href="https://www.youtube.com/@candyheist5270"
                  passHref={true}
                  target="_blank"
                >
                  <div className={styles.contactLogo}>
                    <Youtube />
                  </div>
                </Link>
              </div>
              <p style={{ textAlign: "center", opacity: "0.4" }}>
                © {new Date().getFullYear()} The Formante Recording Services
              </p>
            </div>
          </div>
        </section>
        <ToastContainer />
      </main>
    </>
  );
}
